version: '3.8'

networks: 
  kubenews-network:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kubedevnews
      POSTGRES_PASSWORD: Pg#123
      POSTGRES_DB: kubedevnews
    networks:
      - kubenews-network

  kube-news:
    image: viniciuscaol/kube-news:v1
    container_name: kube-news
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: kubedevnews
      DB_USERNAME: kubedevnews
      DB_PASSWORD: Pg#123
      DB_HOST: postgres
    networks:
      - kubenews-network